### PR TITLE
0.0.10: make sure we've got the latest and greatest!

### PR DESCRIPTION
**Pull request by mrose17**
after the merge, please `npm publish` ... thanks for your patience!

cc: @apexad

### CODE REVIEW

**Comment by apexad** [comment]
So many commits just to bump the version. Glad I helped figure out this needed to be done. Sadly this version of the plugin and node-lightify used have too many other issues for it to be usable to me.

However, if no one beats me to it, I will try to take the good changes from this plugin into rain lake/homebridge-platform-lightify which has no issues that make it unusable.

**Comment by apexad** [comment]
Lots of uneccasary commis.
@chris1705 you just need to bump the version in package.json, then publish to the registry.

**Comment by mrose17** [comment]
only one file has changed: package.json which includes both the version number update *and* a dependency to the version of `node-lightify` that uses a version of `net-socket` that avoids the uncatchable error issue...

**Comment by apexad** [comment]
I see that, but 5 commits!? Perhaps you should squash them.

**Comment by mrose17** [comment]
@chris1705 - i got an RGBW bulb and modified the plugin to support that... enjoy!

**Comment by apexad** [comment]
@mrose17 consider adding this color support to https://github.com/rainlake/homebridge-platform-lightify instead.  As I mentioned in the issue for this, seems like chris1705 has abandoned this plugin, whereas rainlake is still active.

**Comment by mrose17** [comment]
@apexad - i reviewed the package. it already has color support in it. it uses a newer version of `node-lightify` which is good, though neither package currently supports sensors yet...

**Pull request merged**
